package:
  name: pydemux
  version: "v0.0"

source:
  git_tag: v0.0
  git_url: https://github.com/Tee0125/pydemux.git

requirements:
  build:
    - {{ compiler('c') }}
    - python
    - ffmpeg
  run:
    - python
    - ffmpeg
    - pillow

about:
  home: http://github.com/Tee0125/pydemux
  license: LGPL

